name: Platform a11y Tests

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  run_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8']

    name: Python ${{ matrix.python-version }} sample
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '12'

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Setup Gecko Driver
      uses: browser-actions/setup-geckodriver@latest

    - name: Install npm Dependencies
      run: npm install -g rtlcss

    - name: Install Required Packages
      run: |
        sudo apt-get update
        sudo apt-get install -y libxmlsec1-dev memcached
        pip install setuptools wheel
        pip install -r requirements/edx/development.txt
    - name: Run Tests
      run: |
        ./scripts/generic-ci-tests.sh
