on:
  push:
    branches:
    - awais786/mysql-github-actions

jobs:
  run_tests:
    name: a11y Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.8' ]

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '12'

    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Initiate Services
      env:
        DB_DATABASE: edxtest
        DB_USER: root
        DB_PASSWORD: root
      run: |
        sudo apt-get install memcached
        sudo apt-get install python3-lxml
        sudo systemctl start mongod
        sudo service memcached start
        sudo /etc/init.d/mysql start

    - name: Reset mysql password
      run: |
        cat <<EOF | mysql -h 127.0.0.1 -u root --password=root
          UPDATE mysql.user SET authentication_string = null WHERE user = 'root';
          FLUSH PRIVILEGES;
        EOF

    - name: Run Tests
      env:
        TEST_SUITE: a11y
        DB_DATABASE: edxtest
        DB_USER: root
        DB_PASSWORD: ''
      run: |
        sudo service mysql restart
        ./scripts/reset-test-db.sh

#    - name: Install Required Packages
#      run: |
#        sudo apt-get update
#        sudo apt-get install -y libxmlsec1-dev memcached
#        sudo systemctl start mongod
#        sudo service memcached start
#    - name: Install pip
#      run: |
#        pip install setuptools wheel
#        pip install -r requirements/edx/development.txt
#
#    - name: Install Python Dependencies
#      run: pip install -r requirements/edx/development.txt
#    - uses: browser-actions/setup-geckodriver@latest


